Hw 04
ivlytvynets/jv-simple-taxi-service pull request #2
Opened 2021-01-12 18:04 UTC by ivlytvynets

2021-01-12 18:30 UTC, gigbat requested changes

2021-01-12 18:30 UTC, gigbat commented on src/main/java/core/basesyntax/dao/impl/DriverDaoImpl.java
> +        return driver;
```suggestion
        return Storage.addDriver(driver);
```

2021-01-12 18:30 UTC, gigbat commented on src/main/java/core/basesyntax/model/Car.java
> +        checkForNull(manufacturer);
on future, you can use Objects.requireNonNull(param)

2021-01-12 18:42 UTC, gigbat approved these changes

2021-01-13 09:34 UTC, Sofasmile requested changes

2021-01-13 09:34 UTC, Sofasmile commented on src/main/java/core/basesyntax/dao/impl/CarDaoImpl.java
> +                        .contains(driverId))
```suggestion
                        .anyMatch(d -> d.getId().equals(driverId)))
```

2021-01-13 09:34 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Car.java
> +        if (!(checkForNull(model) || checkForNull(manufacturer))) {
подібні перевірки є надлишковими, пропоную їх повністю прибрати зі всіх моделей

2021-01-13 09:34 UTC, Sofasmile commented on src/main/java/core/basesyntax/service/impl/CarServiceImpl.java
> +            carDao.create(car);
давай будемо вважати що на вхід нам приходить уже створена машина
теж саме стосується методу  removeDriverFromCar

2021-01-13 09:34 UTC, Sofasmile commented on src/main/java/core/basesyntax/service/impl/CarServiceImpl.java
> +        carDao.update(car);
```suggestion
        car.getDrivers().add(driver);
        carDao.update(car);
```

2021-01-13 12:16 UTC, Sofasmile requested changes

2021-01-13 12:16 UTC, Sofasmile commented on src/main/java/core/basesyntax/model/Car.java
> +        this.manufacturer = manufacturer;
```suggestion
        this.manufacturer = manufacturer;
        drivers = new ArrayList<>();
```

2021-01-13 12:26 UTC, Sofasmile approved these changes

2021-01-13 12:28 UTC, merged