all is done
ivlytvynets/jv-simple-taxi-service pull request #8
Opened 2021-01-20 21:09 UTC by ivlytvynets

2021-01-20 21:23 UTC, gigbat requested changes
Good job

2021-01-20 21:23 UTC, gigbat commented on src/main/java/core/basesyntax/controllers/cars/AddDriverToCarController.java
> +        Car car = carService.get(carId);
add a check if id not exist

2021-01-20 21:23 UTC, gigbat commented on src/main/java/core/basesyntax/controllers/cars/InjectCarController.java
> +        Long manufacturerId = Long.valueOf(req.getParameter("manufacturer_id"));
same

2021-01-20 21:23 UTC, gigbat commented on src/main/java/core/basesyntax/controllers/drivers/GetAllDriversController.java
> +        req.setAttribute("drivers",drivers);
add space between 2 parameters)

2021-01-20 21:23 UTC, gigbat commented on src/main/webapp/WEB-INF/views/index.jsp
> +<p>
tag "p" need to describe block with text, but if it just link without text you need not to add tag

2021-01-20 21:24 UTC, gigbat requested changes

2021-01-20 21:24 UTC, gigbat commented on src/main/webapp/web.xml
>  </web-app>
add empty line

2021-01-20 21:24 UTC, gigbat commented on src/main/webapp/WEB-INF/views/manufacturers/injectManufacturer.jsp
> +</html>
empty line

2021-01-20 21:24 UTC, gigbat commented on src/main/webapp/WEB-INF/views/index.jsp
>  </html>
empty line

2021-01-20 21:24 UTC, gigbat commented on src/main/webapp/WEB-INF/views/drivers/injectDriver.jsp
> +</html>
empty line

2021-01-20 21:24 UTC, gigbat commented on src/main/webapp/WEB-INF/views/drivers/all.jsp
> +</html>
empty line

2021-01-20 21:24 UTC, gigbat commented on src/main/webapp/WEB-INF/views/cars/injectCar.jsp
> +</html>
empty line

2021-01-20 21:24 UTC, gigbat commented on src/main/webapp/WEB-INF/views/cars/addDriverToCar.jsp
> +</html>
empty line

2021-01-20 22:30 UTC, gigbat approved these changes

2021-01-21 08:05 UTC, KseniiaMakarova requested changes

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/cars/AddDriverToCarController.java
> +            req.setAttribute("message", "Car or driver weren't found");
catching RuntimeException is not a good practice - let's throw custom Exception instead of RuntimeException on DAO layer - or just simply remove these 2 lines

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/cars/AddDriverToCarController.java
> +            req.getRequestDispatcher("/WEB-INF/views/cars/addDriverToCar.jsp").forward(req, resp);
```suggestion
            req.getRequestDispatcher("/WEB-INF/views/cars/addDriverToCar.jsp").forward(req, resp);
            return;
```
we should not be able to move further in this method

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/cars/InjectCarController.java
> +public class InjectCarController extends HttpServlet {
```suggestion
public class CreateCarController extends HttpServlet {
```

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/cars/InjectCarController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/injectCar.jsp").forward(req, resp);
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/cars/create.jsp").forward(req, resp);
```

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/cars/InjectCarController.java
> +            req.getRequestDispatcher("/WEB-INF/views/cars/injectCar.jsp").forward(req, resp);
same here - use `return` and consider not catching RuntimeException

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/drivers/InjectDriverController.java
> +public class InjectDriverController extends HttpServlet {
```suggestion
public class CreateDriverController extends HttpServlet {
```

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/drivers/InjectDriverController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/injectDriver.jsp").forward(req, resp);
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/drivers/create.jsp").forward(req, resp);
```

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/manufacturers/InjectManufacturerController.java
> +public class InjectManufacturerController extends HttpServlet {
same here

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/manufacturers/InjectManufacturerController.java
> +        req.getRequestDispatcher("/WEB-INF/views/manufacturers/injectManufacturer.jsp")
same

2021-01-21 08:05 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/manufacturers/injectManufacturer.jsp
> +<h1>Hello! Enter, please, driver's details:</h1>
```suggestion
<h1>Hello! Enter, please, manufacturer's details:</h1>
```

2021-01-21 11:43 UTC, KseniiaMakarova requested changes

2021-01-21 11:43 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controllers/drivers/CreateDriverController.java
> +        String licenceNumber = req.getParameter("licenceNumber");
```suggestion
        String licenceNumber = req.getParameter("licence_number");
```

2021-01-21 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/cars/addDriverToCar.jsp
> +<h4 style="color:red">${message}</h4>
```suggestion
```

2021-01-21 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/cars/create.jsp
> +<h4 style="color:red">${message}</h4>
```suggestion
```

2021-01-21 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/drivers/create.jsp
> +    Please, enter driver's licence number: <input type="text" name="licenceNumber">
```suggestion
    Please, enter driver's licence number: <input type="text" name="licence_number">
```

2021-01-21 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/index.jsp
> +<a href="${pageContext.request.contextPath}/drivers/all">Get all drivers from DB</a>
```suggestion
<a href="${pageContext.request.contextPath}/drivers/">Get all drivers from DB</a>
```

2021-01-21 11:43 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/drivers/all</url-pattern>
```suggestion
        <url-pattern>/drivers/</url-pattern>
```

2021-01-21 17:40 UTC, KseniiaMakarova approved these changes

2021-01-21 17:42 UTC, merged